ClientEvents.lang('en_us', event => {
  event.renameItem('createdieselgenerators:hammer', 'Industrial Hammer')

  event.renameItem('handcrafted:hammer', 'Furniture Hammer')
  
  event.renameItem('interiors:white_chair', 'White Tall Chair')
  event.renameItem('interiors:orange_chair', 'Orange Tall Chair')
  event.renameItem('interiors:magenta_chair', 'Magenta Tall Chair')
  event.renameItem('interiors:light_blue_chair', 'Light Blue Tall Chair')
  event.renameItem('interiors:yellow_chair', 'Yellow Tall Chair')
  event.renameItem('interiors:lime_chair', 'Lime Tall Chair')
  event.renameItem('interiors:pink_chair', 'Pink Tall Chair')
  event.renameItem('interiors:gray_chair', 'Gray Tall Chair')
  event.renameItem('interiors:light_gray_chair', 'Light Gray Tall Chair')
  event.renameItem('interiors:cyan_chair', 'Cyan Tall Chair')
  event.renameItem('interiors:purple_chair', 'Purple Tall Chair')
  event.renameItem('interiors:blue_chair', 'Blue Tall Chair')
  event.renameItem('interiors:brown_chair', 'Brown Tall Chair')
  event.renameItem('interiors:green_chair', 'Green Tall Chair')
  event.renameItem('interiors:red_chair', 'Red Tall Chair')
  event.renameItem('interiors:black_chair', 'Black Tall Chair')
  event.renameItem('interiors:kelp_chair', 'Kelp Tall Chair')
  
  event.renameItem('interiors:white_cushion', 'White Cushion Block')
  event.renameItem('interiors:orange_cushion', 'Orange Cushion Block')
  event.renameItem('interiors:magenta_cushion', 'Magenta Cushion Block')
  event.renameItem('interiors:light_blue_cushion', 'Light Blue Cushion Block')
  event.renameItem('interiors:yellow_cushion', 'Yellow Cushion Block')
  event.renameItem('interiors:lime_cushion', 'Lime Cushion Block')
  event.renameItem('interiors:pink_cushion', 'Pink Cushion Block')
  event.renameItem('interiors:gray_cushion', 'Gray Cushion Block')
  event.renameItem('interiors:light_gray_cushion', 'Light Gray Cushion Block')
  event.renameItem('interiors:cyan_cushion', 'Cyan Cushion Block')
  event.renameItem('interiors:purple_cushion', 'Purple Cushion Block')
  event.renameItem('interiors:blue_cushion', 'Blue Cushion Block')
  event.renameItem('interiors:brown_cushion', 'Brown Cushion Block')
  event.renameItem('interiors:green_cushion', 'Green Cushion Block')
  event.renameItem('interiors:red_cushion', 'Red Cushion Block')
  event.renameItem('interiors:black_cushion', 'Black Cushion Block')

  event.renameItem('rechiseled:chisel', 'Universal Chisel')
})